export const myBlogs = {
  // delete once blog migrated
  featured: [
    {
      id: 1,
      title: "Blog Hosted via Hashnode",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1647626775/portfolio%20site/Screen_Shot_2022-03-18_at_14.06.02_nsptaw.png",
      desc: "Currently In the process of migrating my blog to my site. In the meantime you can view my full blog via Hashnode. Thank you for your patience.",
      link: "https://webdevchris1.hashnode.dev/",
    },
  ],
  blogs: [
    {
      id: 1,
      title: "Day 0 - Prologue",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-prologue",
      favorite: false,
      featured: false,
    },
    {
      id: 2,
      title: "Day 1 - CSS Grid Practice",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-1",
      favorite: false,
      featured: false,
    },
    {
      id: 3,
      title: "Day 2 - Footers and Font Awesome",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-2",
      favorite: false,
      featured: false,
    },
    {
      id: 4,
      title: "Day 3 - Footer Completed!",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-3",
      favorite: false,
      featured: false,
    },
    {
      id: 5,
      title: "Day 4 - Media Query Issues",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-developer-day-4",
      favorite: false,
      featured: false,
    },

    {
      id: 6,
      title: "Day 5 - Navbar Fixed",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-5",
      favorite: false,
      featured: false,
    },
    {
      id: 7,
      title: "Day 6 - Media Queries The Right Way",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-6",
      favorite: true,
      featured: false,
    },
    {
      id: 8,
      title: "Day 7 - Masonry Grid Site Completed",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-7",
      favorite: false,
      featured: false,
    },
    {
      id: 9,
      title: "Day 8 - Professional Image Building",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-8",
      favorite: false,
      featured: false,
    },
    {
      id: 10,
      title: "Day 9 - HTML Review",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-9",
      favorite: false,
      featured: false,
    },
    {
      id: 11,
      title: "Day 10 - Mental Break",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-10",
      favorite: false,
      featured: false,
    },
    {
      id: 12,
      title: "Day 11 - HTML Exercises, Quiz and a New Project!",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-11",
      favorite: true,
      featured: false,
    },
    {
      id: 13,
      title: "Day 12 - Periodic Table and Spellcheck Project Completed",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-12",
      favorite: false,
      featured: false,
    },
    {
      id: 14,
      title: "Day 13 - Quick Practice & Glassmorphism",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-13",
      favorite: false,
      featured: false,
    },
    {
      id: 15,
      title: "Day 14 - Transition Effects",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-14",
      favorite: false,
      featured: false,
    },
    {
      id: 16,
      title: "Day 15 - Getting Used to Media Queries",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-15",
      favorite: false,
      featured: false,
    },
    {
      id: 17,
      title: "Day 16 - Twitter Header/Banner",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-16",
      favorite: false,
      featured: false,
    },
    {
      id: 18,
      title: "Day 17 - FreeCodeCamp Review Day",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-17",
      favorite: false,
      featured: false,
    },
    {
      id: 19,
      title: "Day 18 - More Review and Night Sky Project!",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-18",
      favorite: false,
      featured: false,
    },
    {
      id: 20,
      title: "Day 19 - CSS Animation Practice",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-19",
      favorite: false,
      featured: false,
    },
    {
      id: 21,
      title: "Day 20 - Night Sky Project Completed!",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-20",
      favorite: false,
      featured: false,
    },
    {
      id: 22,
      title: "Day 21 - Creativity Block",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-21",
      favorite: false,
      featured: false,
    },
    {
      id: 23,
      title: "Day 22 & 23 - Creativity Block Continues...",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-22-and-23",
      favorite: false,
      featured: false,
    },
    {
      id: 24,
      title: "Day 24 - No more Creative Block!",
      link: "https://webdevchris1.hashnode.dev/day-24-no-more-creative-block",
      favorite: false,
      featured: false,
    },
    {
      id: 25,
      title: "Day 25 - Portfolio Site Almost Done!",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-25",
      favorite: false,
      featured: false,
    },
    {
      id: 26,
      title: "Day 26 - Busy Start For July",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-prologue",
      favorite: false,
      featured: false,
    },
    {
      id: 27,
      title: "Day 27 - To Do List Project",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-27",
      favorite: true,
      featured: false,
    },
    {
      id: 28,
      title: "Day 28 - Problems Solutions and More Problems",
      link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-28",
      favorite: false,
      featured: false,
    },
  ],
};

// export const featured = {
//   id: 1,
//   title: "Blog Hosted via Hashnode",
//   img: "https://res.cloudinary.com/webdevchris/image/upload/v1647626775/portfolio%20site/Screen_Shot_2022-03-18_at_14.06.02_nsptaw.png",
//   desc: "Currently In the process of migrating my blog to my site. In the meantime you can view my full blog via Hashnode. Thank you for your patience.",
//   link: "https://webdevchris1.hashnode.dev/",
// };

// export const favorites = [
//   {
//     id: 1,
//     title: "Day 7 - Masonry Grid Site Completed",
//     link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-7",
//   },
//   {
//     id: 2,
//     title: "Day 11 - HTML Exercises, Quiz and a New Project!",
//     link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-11",
//   },
//   {
//     id: 3,
//     title: "Day 27 - To Do List Project",
//     link: "https://webdevchris1.hashnode.dev/becoming-a-front-end-dev-day-27",
//   },
// ];
