const myProjects = {
  apiProjects: [
    {
      id: 1,
      title: "Movie Database",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069664/portfolio%20site/movie_vutbfq.png",
      desc: "Using Movie Database API, search your favorite movies to learn more about it",
      link: "https://webdevchris-movies.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 2,
      title: "Cocktail Database",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069662/portfolio%20site/cocktail_y0lsiq.png",
      desc: "Using Cocktail Database API, search your favorite drinks and learn how to make them",
      link: "https://webdevchris-cocktail-db.netlify.app",
      code: "https://www.google.com",
    },
  ],
  userProjects: [
    {
      id: 1,
      title: "Shopping Cart",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069661/portfolio%20site/cart_w94mgp.png",
      desc: "Example of a shopping cart page for an e-commerce website",
      link: "https://webdevchris-shopping-cart.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 2,
      title: "Restaurant Menu",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069662/portfolio%20site/menu_xuwb8x.png",
      desc: "Example of a food menu page for a restaurant's website. Including filtering",
      link: "https://webdevchris-menu.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 3,
      title: "Slider",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069661/portfolio%20site/slider_rfyylh.png",
      desc: "Display information one at a time with user functionalty to change the current tab",
      link: "https://webdevchris-slider.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 4,
      title: "Navbar",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645679799/portfolio%20site/navbar_byf6lq.png",
      desc: "See how this navbar changes based on your viewing window size",
      link: "https://webdevchris-navbar.netlify.app/",
      code: "https://github.com/WebDevChris1/Navbar/",
    },
    {
      id: 5,
      title: "Collection Page",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645374658/portfolio%20site/collection_page_coflxw.png",
      desc: "Display all your products and/or services on one page",
      link: "https://webdevchris-collection-page.netlify.app/",
      code: "https://github.com/WebDevChris1/product-page",
    },

    {
      id: 6,
      title: "Rude Bunny",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645678271/portfolio%20site/rude_bunny_m0mpoj.png",
      desc: "Hover over the bunny for a message",
      link: "https://webdevchris-rude-bunny.netlify.app/",
      code: "https://github.com/WebDevChris1/Rude-Bunny",
    },
    {
      id: 7,
      title: "Quiz",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645072103/portfolio%20site/quiz_ygkfb9.png",
      desc: "Created this app to demonstrate my ability to have a program react based on user selection",
      link: "https://webdevchris-quiz.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 8,
      title: "Glass Morphism Cards",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645371911/portfolio%20site/Glass-Morphism-cards_vpbpuz.png",
      desc: "Display your team members information with a stylish look and hover effects",
      link: "https://webdevchris-glass-morphism-cards.netlify.app/",
      code: "https://github.com/WebDevChris1/Glassmorphism-Cards",
    },
    {
      id: 9,
      title: "Sign Up Page",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645372576/portfolio%20site/Signup_acrbur.png",
      desc: "Add a clean sign up page design to your website",
      link: "https://webdevchris-sign-up.netlify.app/",
      code: "https://github.com/WebDevChris1/Signup-Page",
    },
    {
      id: 10,
      title: "Login Page",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645372756/portfolio%20site/Login_timiuk.png",
      desc: "Add a clean login page design to your website",
      link: "https://webdevchris-log-in.netlify.app/",
      code: "https://github.com/WebDevChris1/Login-Page-Auth",
    },

    {
      id: 11,
      title: "Tribute Page",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645373143/portfolio%20site/WW2_ajym1k.png",
      desc: "Blog site for major events that occured in World War 2",
      link: "https://webdevchris-ww2-events.netlify.app/",
      code: "https://github.com/WebDevChris1/Tribute-Page",
    },

    {
      id: 12,
      title: "Email Collector",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645373536/portfolio%20site/email-collector_sdf7nq.png",
      desc: "Add a clean email collector design to your website",
      link: "https://webdevchris-email-collector.netlify.app/",
      code: "https://github.com/WebDevChris1/Email-Collector",
    },
  ],
  toolProjects: [
    {
      id: 1,
      title: "Grocery List",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069660/portfolio%20site/grocery_k1ucsn.png",
      desc: "Created an app to keep track of what is needed from the grocery store",
      link: "https://webdevchris-grocery-list.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 2,
      title: "Color Generator",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069661/portfolio%20site/color-gen_zifztz.png",
      desc: "Created an app to reccomend like HEX colors based on an input",
      link: "https://webdevchris-color-gen.netlify.app/",
      code: "https://www.google.com",
    },
    {
      id: 3,
      title: "Shopify Link Grabber",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645069661/portfolio%20site/link_rxc2j7.png",
      desc: "Enter a shopify website url which then returns information for all products listed on the site",
      link: "https://webdevchris-shopify-links.netlify.app/",
      code: "https://github.com/WebDevChris1/shopify-product-grabber",
    },
    {
      id: 4,
      title: "Spellcheck",
      img: "https://res.cloudinary.com/webdevchris/image/upload/v1645677966/portfolio%20site/spellcheck_m0ea23.png",
      desc: "Never misspell a word again",
      link: "https://webdevchris-spell-check.netlify.app/",
      code: "https://github.com/WebDevChris1/Spell-Check",
    },
  ],
};

export default myProjects;
